packages:
  - apps/*
  - packages/*
  - tooling/*
  - playground/*
catalog:
  '@auth/core': 0.37.2
  '@auth/drizzle-adapter': ~1.7.4
  next-auth: 5.0.0-beta.25
  eslint: ^9.19.0
  eslint-config-next: 15.2.4
  prettier: ^3.4.2
  tailwindcss: ^4
  '@tailwindcss/postcss': ^4
  typescript: ^5.8.2
  '@types/node': ^22.13.11
  '@hookform/resolvers': ^4.1.3
  react-hook-form: ^7.54.2
  next-themes: ^0.4.6
  zod: ^3.25.16
  next: 15.2.4
  '@standard-schema/spec': ^1.0.0
  '@tanstack/react-query': ^5.67.1
  '@trpc/client': ^11.0.0-rc.824
  '@trpc/tanstack-react-query': ^11.0.0-rc.824
  '@trpc/server': ^11.0.0-rc.824
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^19.0.12
    '@types/react-dom': ^19.0.4
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - bufferutil
  - core-js-pure
  - esbuild
  - prisma
  - sharp
