packages:
  - apps/*
  - packages/*
  - tooling/*
  - playground/*
  - packages/ts-rest/src/schemas/adapters/zod
catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  "@types/react": ^19.1.6
  "@types/react-dom": ^19.1.5
  "@auth/core": 0.37.2
  "@auth/drizzle-adapter": ~1.7.4
  next-auth: 5.0.0-beta.25
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^4
  "@tailwindcss/postcss": ^4
  typescript: ^5.8.2
  "@types/node": ^22.13.11
  "@hookform/resolvers": ^4.1.3
  react-hook-form: ^7.57.0
  next-themes: ^0.4.6
  zod: ^3.25.48
  # https://github.com/vercel/next.js/discussions/71727
  next: ^15.4.0-canary.85
  eslint-config-next: ^15.4.0-canary.85
  "@standard-schema/spec": ^1.0.0
  "@tanstack/react-query": ^5.67.1
  "@trpc/client": ^11.0.0-rc.824
  "@trpc/tanstack-react-query": ^11.0.0-rc.824
  "@trpc/server": ^11.0.0-rc.824
  mutative: ^1.2.0 # https://www.npmjs.com/package/mutative
  zustand-mutative: ^1.3.0 # https://www.npmjs.com/package/zustand-mutative
  zustand: ^5.0.5 # https://www.npmjs.com/package/zustand
catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - "@clerk/shared"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - bufferutil
  - core-js-pure
  - esbuild
  - prisma
  - sharp
