packages:
  - apps/*
  - packages/*
  - tooling/*
  - packages/ts-rest/src/schemas/adapters/zod

catalog:
  '@auth/core': 0.37.2
  '@auth/drizzle-adapter': ~1.7.4
  '@biomejs/biome': ^2.2.0
  '@hookform/resolvers': ^4.1.3
  '@orpc/client': ^1.8.3
  '@orpc/openapi': ^1.8.3
  '@orpc/server': ^1.8.3
  '@orpc/tanstack-query': ^1.8.3
  '@orpc/zod': ^1.8.3
  '@solidjs/meta': ^0.29.4
  '@solidjs/router': ^0.15.0
  '@solidjs/start': ^1.1.0
  '@standard-schema/spec': ^1.0.0
  '@tailwindcss/postcss': ^4
  '@tanstack/react-query': ^5.67.1
  '@tanstack/solid-query': ^5.85.5
  '@tanstack/solid-query-devtools': ^5.85.5
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  '@trpc/tanstack-react-query': ^11.5.0
  '@types/node': ^22.17.2
  '@types/pg': ^8.15.5
  '@types/react': ^19.1.11
  '@types/react-dom': ^19.1.7
  drizzle-kit: ^0.31.2
  drizzle-orm: ^0.44.2
  drizzle-zod: ^0.6.1
  eslint: ^9.19.0
  eslint-config-next: ^15.5.0
  mutative: ^1.2.0
  next: ^15.5.0
  next-auth: 5.0.0-beta.25
  next-themes: ^0.4.6
  pg: ^8.14.1
  prettier: ^3.4.2
  react: ^19.1.1
  react-dom: ^19.1.1
  react-hook-form: ^7.62.0
  solid-js: ^1.9.9
  tailwindcss: ^4.1.12
  tsx: ^4.20.4
  typescript: ^5.9.2
  uuid: ^11.1.0
  vinxi: ^0.5.7
  vite: ^7.0.2
  zod: ^4.0.17
  zustand: ^5.0.8
  zustand-mutative: ^1.3.0

catalogs:
  react19:
    '@types/react': ^19.1.11
    '@types/react-dom': ^19.1.7
    react: ^19.1.1
    react-dom: ^19.1.1

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bufferutil
  - core-js-pure
  - esbuild
  - prisma
  - sharp
